export const FACEBOOK_URL = 'https://www.facebook.com/Aries-Living-112940767034421/'
export const TWITTER_USER_NAME = 'https://twitter.com/aries_living'
export const INSTAGRAM_USER_NAME = 'https://instagram.com/ariesliving'
export const NAME_SHORT = 'Villa Paradiso'
export const NAME_LONG = 'Apartment Hotel Miami'
export const LLC_NAME = '1415 Collins Ave YT AL LLC'
export const EMAIL_ADDRESS = 'villaparadiso@ariesliving.com'
export const PHONE_NUMBER = '+1 (813) 575-4532'
export const PLATFORM_LOWERCASE = 'villa paradiso'
export const ADDRESS_TOP = '1415 Collins Ave'
export const ADDRESS_BOTTOM = 'Miami Beach, FL 33139'
export const PLATFORM_URL = 'https://villaparadisohotels.com'
export const defaultOgImage =
  'https://res.cloudinary.com/dqtpoczux/image/upload/v1595509416/2_vmy4ul.png'
