export default [
  { src: '/showcase-thumbnails/exterior/1.jpg', alt: 'Exterior 1' },
  { src: '/showcase-thumbnails/exterior/2.jpg', alt: 'Exterior 2' },
  { src: '/showcase-thumbnails/exterior/3.jpg', alt: 'Exterior 3' },
  { src: '/showcase-thumbnails/exterior/4.jpg', alt: 'Exterior 4' },
  { src: '/showcase-thumbnails/rooms/multi-unit/1.jpg', alt: 'Multi-Unit - 1' },
  { src: '/showcase-thumbnails/rooms/multi-unit/2.jpg', alt: 'Multi-Unit - 2' },
  { src: '/showcase-thumbnails/rooms/multi-unit/3.jpg', alt: 'Multi-Unit - 3' },
  { src: '/showcase-thumbnails/rooms/multi-unit/4.jpg', alt: 'Multi-Unit - 4' },
  { src: '/showcase-thumbnails/rooms/multi-unit/5.jpg', alt: 'Multi-Unit - 5' },
  { src: '/showcase-thumbnails/rooms/multi-unit/6.jpg', alt: 'Multi-Unit - 6' },
  { src: '/showcase-thumbnails/rooms/multi-unit/7.jpg', alt: 'Multi-Unit - 7' },
  { src: '/showcase-thumbnails/rooms/multi-unit/8.jpg', alt: 'Multi-Unit - 8' },
  { src: '/showcase-thumbnails/rooms/multi-unit/9.jpg', alt: 'Multi-Unit - 9' },
  { src: '/showcase-thumbnails/rooms/multi-unit/15/1.jpg', alt: 'Multi-Unit - 15 - 1' },
  { src: '/showcase-thumbnails/rooms/multi-unit/15/2.jpg', alt: 'Multi-Unit - 15 - 2' },
  { src: '/showcase-thumbnails/rooms/multi-unit/15/3.jpg', alt: 'Multi-Unit - 15 - 3' },
  { src: '/showcase-thumbnails/rooms/multi-unit/15/4.jpg', alt: 'Multi-Unit - 15 - 4' },
  { src: '/showcase-thumbnails/rooms/multi-unit/15/5.jpg', alt: 'Multi-Unit - 15 - 5' },
  { src: '/showcase-thumbnails/rooms/multi-unit/15/6.jpg', alt: 'Multi-Unit - 15 - 6' },
  { src: '/showcase-thumbnails/rooms/multi-unit/15/7.jpg', alt: 'Multi-Unit - 15 - 7' },
  { src: '/showcase-thumbnails/rooms/multi-unit/15/8.jpg', alt: 'Multi-Unit - 15 - 8' },
  { src: '/showcase-thumbnails/rooms/multi-unit/15/9.jpg', alt: 'Multi-Unit - 15 - 9' },
  { src: '/showcase-thumbnails/rooms/multi-unit/15/10.jpg', alt: 'Multi-Unit - 15 - 10' },
  { src: '/showcase-thumbnails/rooms/multi-unit/15/11.jpg', alt: 'Multi-Unit - 15 - 11' },
  { src: '/showcase-thumbnails/rooms/16/1.jpg', alt: 'Room 16 - 1' },
  { src: '/showcase-thumbnails/rooms/16/2.jpg', alt: 'Room 16 - 2' },
  { src: '/showcase-thumbnails/rooms/16/3.jpg', alt: 'Room 16 - 3' },
  { src: '/showcase-thumbnails/rooms/16/4.jpg', alt: 'Room 16 - 4' },
  { src: '/showcase-thumbnails/rooms/16/5.jpg', alt: 'Room 16 - 5' },
  { src: '/showcase-thumbnails/rooms/16/6.jpg', alt: 'Room 16 - 6' },
  { src: '/showcase-thumbnails/rooms/16/7.jpg', alt: 'Room 16 - 7' },
  { src: '/showcase-thumbnails/rooms/16/8.jpg', alt: 'Room 16 - 8' },
  { src: '/showcase-thumbnails/rooms/16/9.jpg', alt: 'Room 16 - 9' },
  { src: '/showcase-thumbnails/rooms/16/10.jpg', alt: 'Room 16 - 10' },
  { src: '/showcase-thumbnails/rooms/18/1.jpg', alt: 'Room 18 - 1' },
  { src: '/showcase-thumbnails/rooms/18/2.jpg', alt: 'Room 18 - 2' },
  { src: '/showcase-thumbnails/rooms/18/3.jpg', alt: 'Room 18 - 3' },
  { src: '/showcase-thumbnails/rooms/18/4.jpg', alt: 'Room 18 - 4' },
  { src: '/showcase-thumbnails/rooms/19/1.jpg', alt: 'Room 19 - 1' },
  { src: '/showcase-thumbnails/rooms/19/2.jpg', alt: 'Room 19 - 2' },
  { src: '/showcase-thumbnails/rooms/19/3.jpg', alt: 'Room 19 - 3' },
  { src: '/showcase-thumbnails/rooms/19/4.jpg', alt: 'Room 19 - 4' },
  { src: '/showcase-thumbnails/rooms/19/5.jpg', alt: 'Room 19 - 5' },
  { src: '/showcase-thumbnails/rooms/19/6.jpg', alt: 'Room 19 - 6' },
  { src: '/showcase-thumbnails/rooms/19/7.jpg', alt: 'Room 19 - 7' },
  { src: '/showcase-thumbnails/rooms/19/8.jpg', alt: 'Room 19 - 8' },
  { src: '/showcase-thumbnails/rooms/19/9.jpg', alt: 'Room 19 - 9' },
  { src: '/showcase-thumbnails/rooms/19/10.jpg', alt: 'Room 19 - 10' },
  { src: '/showcase-thumbnails/rooms/19/11.jpg', alt: 'Room 19 - 11' },
  { src: '/showcase-thumbnails/rooms/19/12.jpg', alt: 'Room 19 - 12' },
  { src: '/showcase-thumbnails/rooms/19/13.jpg', alt: 'Room 19 - 13' },
  { src: '/showcase-thumbnails/rooms/1/1.jpg', alt: 'Room 1 - 1' },
  { src: '/showcase-thumbnails/rooms/1/2.jpg', alt: 'Room 1 - 2' },
  { src: '/showcase-thumbnails/rooms/1/3.jpg', alt: 'Room 1 - 3' },
  { src: '/showcase-thumbnails/rooms/1/4.jpg', alt: 'Room 1 - 4' },
  { src: '/showcase-thumbnails/rooms/1/5.jpg', alt: 'Room 1 - 5' },
  { src: '/showcase-thumbnails/rooms/1/6.jpg', alt: 'Room 1 - 6' },
  { src: '/showcase-thumbnails/rooms/1/7.jpg', alt: 'Room 1 - 7' },
  { src: '/showcase-thumbnails/rooms/1/8.jpg', alt: 'Room 1 - 8' },
  { src: '/showcase-thumbnails/rooms/1/9.jpg', alt: 'Room 1 - 9' },
  { src: '/showcase-thumbnails/shared/closet.jpg', alt: 'Closet' }
]
